axis_linear: 1  # Left thumb stick vertical
scale_linear: 0.2
scale_linear_turbo: 1.5

axis_angular: 0  # Left thumb stick horizontal
scale_angular: 1.0

enable_button: 6  # Left trigger button
enable_turbo_button: -1
